server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/Keepnote
        username: root
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: create
        openInView: false
        show_sql: true
